# Generated by Django 5.2 on 2025-04-21 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('is_premature', models.BooleanField(default=False)),
                ('gestation_weeks', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age_weeks', models.IntegerField()),
                ('weight', models.FloatField(help_text='Peso en gramos')),
                ('height', models.FloatField(help_text='Altura en centímetros')),
                ('head_circumference', models.FloatField(help_text='Perímetro craneal en centímetros')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.baby')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_weeks', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('measure_type', models.CharField(choices=[('weight', 'Peso'), ('height', 'Altura'), ('head', 'Perímetro Craneal')], max_length=10)),
                ('percentile', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('age_weeks', 'gender', 'measure_type', 'percentile')},
            },
        ),
    ]
